// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/discord.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/discord.go -destination=internal/usecase/mock/mock_discord_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordRepository is a mock of DiscordRepository interface.
type MockDiscordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordRepositoryMockRecorder
	isgomock struct{}
}

// MockDiscordRepositoryMockRecorder is the mock recorder for MockDiscordRepository.
type MockDiscordRepositoryMockRecorder struct {
	mock *MockDiscordRepository
}

// NewMockDiscordRepository creates a new mock instance.
func NewMockDiscordRepository(ctrl *gomock.Controller) *MockDiscordRepository {
	mock := &MockDiscordRepository{ctrl: ctrl}
	mock.recorder = &MockDiscordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordRepository) EXPECT() *MockDiscordRepositoryMockRecorder {
	return m.recorder
}

// FetchDiscordUser mocks base method.
func (m *MockDiscordRepository) FetchDiscordUser(ctx context.Context, token entity.DiscordToken) (entity.DiscordUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDiscordUser", ctx, token)
	ret0, _ := ret[0].(entity.DiscordUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDiscordUser indicates an expected call of FetchDiscordUser.
func (mr *MockDiscordRepositoryMockRecorder) FetchDiscordUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDiscordUser", reflect.TypeOf((*MockDiscordRepository)(nil).FetchDiscordUser), ctx, token)
}

// GetAllowedDiscordGuilds mocks base method.
func (m *MockDiscordRepository) GetAllowedDiscordGuilds(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedDiscordGuilds", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedDiscordGuilds indicates an expected call of GetAllowedDiscordGuilds.
func (mr *MockDiscordRepositoryMockRecorder) GetAllowedDiscordGuilds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedDiscordGuilds", reflect.TypeOf((*MockDiscordRepository)(nil).GetAllowedDiscordGuilds), ctx)
}

// GetDiscordAuthURL mocks base method.
func (m *MockDiscordRepository) GetDiscordAuthURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordAuthURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordAuthURL indicates an expected call of GetDiscordAuthURL.
func (mr *MockDiscordRepositoryMockRecorder) GetDiscordAuthURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordAuthURL", reflect.TypeOf((*MockDiscordRepository)(nil).GetDiscordAuthURL), ctx)
}

// GetDiscordClientID mocks base method.
func (m *MockDiscordRepository) GetDiscordClientID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordClientID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordClientID indicates an expected call of GetDiscordClientID.
func (mr *MockDiscordRepositoryMockRecorder) GetDiscordClientID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordClientID", reflect.TypeOf((*MockDiscordRepository)(nil).GetDiscordClientID), ctx)
}

// GetDiscordGuilds mocks base method.
func (m *MockDiscordRepository) GetDiscordGuilds(ctx context.Context, token entity.DiscordToken) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordGuilds", ctx, token)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordGuilds indicates an expected call of GetDiscordGuilds.
func (mr *MockDiscordRepositoryMockRecorder) GetDiscordGuilds(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordGuilds", reflect.TypeOf((*MockDiscordRepository)(nil).GetDiscordGuilds), ctx, token)
}

// GetDiscordToken mocks base method.
func (m *MockDiscordRepository) GetDiscordToken(ctx context.Context, code string) (entity.DiscordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordToken", ctx, code)
	ret0, _ := ret[0].(entity.DiscordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordToken indicates an expected call of GetDiscordToken.
func (mr *MockDiscordRepositoryMockRecorder) GetDiscordToken(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordToken", reflect.TypeOf((*MockDiscordRepository)(nil).GetDiscordToken), ctx, code)
}

// GetHostURL mocks base method.
func (m *MockDiscordRepository) GetHostURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostURL indicates an expected call of GetHostURL.
func (mr *MockDiscordRepositoryMockRecorder) GetHostURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostURL", reflect.TypeOf((*MockDiscordRepository)(nil).GetHostURL), ctx)
}
