// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/work.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/work.go -destination=internal/usecase/mock/mock_work_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkRepository is a mock of WorkRepository interface.
type MockWorkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkRepositoryMockRecorder is the mock recorder for MockWorkRepository.
type MockWorkRepositoryMockRecorder struct {
	mock *MockWorkRepository
}

// NewMockWorkRepository creates a new mock instance.
func NewMockWorkRepository(ctrl *gomock.Controller) *MockWorkRepository {
	mock := &MockWorkRepository{ctrl: ctrl}
	mock.recorder = &MockWorkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkRepository) EXPECT() *MockWorkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkRepository) Create(ctx context.Context, work *entity.Work) (*entity.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, work)
	ret0, _ := ret[0].(*entity.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkRepositoryMockRecorder) Create(ctx, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkRepository)(nil).Create), ctx, work)
}

// ExistsById mocks base method.
func (m *MockWorkRepository) ExistsById(ctx context.Context, id uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsById", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsById indicates an expected call of ExistsById.
func (mr *MockWorkRepositoryMockRecorder) ExistsById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsById", reflect.TypeOf((*MockWorkRepository)(nil).ExistsById), ctx, id)
}

// GetAll mocks base method.
func (m *MockWorkRepository) GetAll(ctx context.Context, limit, offset int) ([]*entity.Work, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.Work)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWorkRepositoryMockRecorder) GetAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWorkRepository)(nil).GetAll), ctx, limit, offset)
}

// GetByID mocks base method.
func (m *MockWorkRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkRepository)(nil).GetByID), ctx, id)
}
