// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/favorite.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/favorite.go -destination=internal/usecase/mock/mock_favorite_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockFavoriteRepository is a mock of FavoriteRepository interface.
type MockFavoriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteRepositoryMockRecorder
	isgomock struct{}
}

// MockFavoriteRepositoryMockRecorder is the mock recorder for MockFavoriteRepository.
type MockFavoriteRepositoryMockRecorder struct {
	mock *MockFavoriteRepository
}

// NewMockFavoriteRepository creates a new mock instance.
func NewMockFavoriteRepository(ctrl *gomock.Controller) *MockFavoriteRepository {
	mock := &MockFavoriteRepository{ctrl: ctrl}
	mock.recorder = &MockFavoriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteRepository) EXPECT() *MockFavoriteRepositoryMockRecorder {
	return m.recorder
}

// CountByWorkID mocks base method.
func (m *MockFavoriteRepository) CountByWorkID(ctx context.Context, workID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByWorkID", ctx, workID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByWorkID indicates an expected call of CountByWorkID.
func (mr *MockFavoriteRepositoryMockRecorder) CountByWorkID(ctx, workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByWorkID", reflect.TypeOf((*MockFavoriteRepository)(nil).CountByWorkID), ctx, workID)
}

// Create mocks base method.
func (m *MockFavoriteRepository) Create(ctx context.Context, favorite *entity.Favorite) (*entity.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, favorite)
	ret0, _ := ret[0].(*entity.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFavoriteRepositoryMockRecorder) Create(ctx, favorite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFavoriteRepository)(nil).Create), ctx, favorite)
}

// Delete mocks base method.
func (m *MockFavoriteRepository) Delete(ctx context.Context, favorite *entity.Favorite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, favorite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFavoriteRepositoryMockRecorder) Delete(ctx, favorite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFavoriteRepository)(nil).Delete), ctx, favorite)
}

// Exists mocks base method.
func (m *MockFavoriteRepository) Exists(ctx context.Context, favorite *entity.Favorite) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, favorite)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockFavoriteRepositoryMockRecorder) Exists(ctx, favorite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFavoriteRepository)(nil).Exists), ctx, favorite)
}
