// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/favorite.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/favorite.go -destination=internal/interface/controller/mock/mock_favorite_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIFavoriteUsecase is a mock of IFavoriteUsecase interface.
type MockIFavoriteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIFavoriteUsecaseMockRecorder
	isgomock struct{}
}

// MockIFavoriteUsecaseMockRecorder is the mock recorder for MockIFavoriteUsecase.
type MockIFavoriteUsecaseMockRecorder struct {
	mock *MockIFavoriteUsecase
}

// NewMockIFavoriteUsecase creates a new mock instance.
func NewMockIFavoriteUsecase(ctrl *gomock.Controller) *MockIFavoriteUsecase {
	mock := &MockIFavoriteUsecase{ctrl: ctrl}
	mock.recorder = &MockIFavoriteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFavoriteUsecase) EXPECT() *MockIFavoriteUsecaseMockRecorder {
	return m.recorder
}

// CountFavoritesByWorkID mocks base method.
func (m *MockIFavoriteUsecase) CountFavoritesByWorkID(ctx context.Context, workID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFavoritesByWorkID", ctx, workID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFavoritesByWorkID indicates an expected call of CountFavoritesByWorkID.
func (mr *MockIFavoriteUsecaseMockRecorder) CountFavoritesByWorkID(ctx, workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFavoritesByWorkID", reflect.TypeOf((*MockIFavoriteUsecase)(nil).CountFavoritesByWorkID), ctx, workID)
}

// CreateFavorite mocks base method.
func (m *MockIFavoriteUsecase) CreateFavorite(ctx context.Context, workID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavorite", ctx, workID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFavorite indicates an expected call of CreateFavorite.
func (mr *MockIFavoriteUsecaseMockRecorder) CreateFavorite(ctx, workID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavorite", reflect.TypeOf((*MockIFavoriteUsecase)(nil).CreateFavorite), ctx, workID, userID)
}

// DeleteFavorite mocks base method.
func (m *MockIFavoriteUsecase) DeleteFavorite(ctx context.Context, workID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavorite", ctx, workID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFavorite indicates an expected call of DeleteFavorite.
func (mr *MockIFavoriteUsecaseMockRecorder) DeleteFavorite(ctx, workID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavorite", reflect.TypeOf((*MockIFavoriteUsecase)(nil).DeleteFavorite), ctx, workID, userID)
}

// IsFavorite mocks base method.
func (m *MockIFavoriteUsecase) IsFavorite(ctx context.Context, workID, userID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFavorite", ctx, workID, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFavorite indicates an expected call of IsFavorite.
func (mr *MockIFavoriteUsecaseMockRecorder) IsFavorite(ctx, workID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavorite", reflect.TypeOf((*MockIFavoriteUsecase)(nil).IsFavorite), ctx, workID, userID)
}
