// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/asset.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/asset.go -destination=internal/interface/controller/mock/mock_asset_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssetUseCase is a mock of IAssetUseCase interface.
type MockIAssetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIAssetUseCaseMockRecorder
	isgomock struct{}
}

// MockIAssetUseCaseMockRecorder is the mock recorder for MockIAssetUseCase.
type MockIAssetUseCaseMockRecorder struct {
	mock *MockIAssetUseCase
}

// NewMockIAssetUseCase creates a new mock instance.
func NewMockIAssetUseCase(ctrl *gomock.Controller) *MockIAssetUseCase {
	mock := &MockIAssetUseCase{ctrl: ctrl}
	mock.recorder = &MockIAssetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssetUseCase) EXPECT() *MockIAssetUseCaseMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockIAssetUseCase) UploadFile(ctx context.Context, file *multipart.FileHeader, userID string) (*entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, userID)
	ret0, _ := ret[0].(*entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockIAssetUseCaseMockRecorder) UploadFile(ctx, file, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockIAssetUseCase)(nil).UploadFile), ctx, file, userID)
}
