// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/comment.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/comment.go -destination=internal/interface/controller/mock/mock_comment_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockICommentUsecase is a mock of ICommentUsecase interface.
type MockICommentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockICommentUsecaseMockRecorder
	isgomock struct{}
}

// MockICommentUsecaseMockRecorder is the mock recorder for MockICommentUsecase.
type MockICommentUsecaseMockRecorder struct {
	mock *MockICommentUsecase
}

// NewMockICommentUsecase creates a new mock instance.
func NewMockICommentUsecase(ctrl *gomock.Controller) *MockICommentUsecase {
	mock := &MockICommentUsecase{ctrl: ctrl}
	mock.recorder = &MockICommentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommentUsecase) EXPECT() *MockICommentUsecaseMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockICommentUsecase) CreateComment(ctx context.Context, content string, workID, userID uuid.UUID, replyAt string) (*entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, content, workID, userID, replyAt)
	ret0, _ := ret[0].(*entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockICommentUsecaseMockRecorder) CreateComment(ctx, content, workID, userID, replyAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockICommentUsecase)(nil).CreateComment), ctx, content, workID, userID, replyAt)
}

// GetCommentsByWorkID mocks base method.
func (m *MockICommentUsecase) GetCommentsByWorkID(ctx context.Context, workID uuid.UUID) ([]*entity.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByWorkID", ctx, workID)
	ret0, _ := ret[0].([]*entity.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByWorkID indicates an expected call of GetCommentsByWorkID.
func (mr *MockICommentUsecaseMockRecorder) GetCommentsByWorkID(ctx, workID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByWorkID", reflect.TypeOf((*MockICommentUsecase)(nil).GetCommentsByWorkID), ctx, workID)
}
