// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth.go -destination=internal/interface/controller/mock/mock_auth_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAuthUsecase is a mock of IAuthUsecase interface.
type MockIAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthUsecaseMockRecorder
	isgomock struct{}
}

// MockIAuthUsecaseMockRecorder is the mock recorder for MockIAuthUsecase.
type MockIAuthUsecaseMockRecorder struct {
	mock *MockIAuthUsecase
}

// NewMockIAuthUsecase creates a new mock instance.
func NewMockIAuthUsecase(ctrl *gomock.Controller) *MockIAuthUsecase {
	mock := &MockIAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockIAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthUsecase) EXPECT() *MockIAuthUsecaseMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockIAuthUsecase) AuthenticateUser(ctx context.Context, code string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockIAuthUsecaseMockRecorder) AuthenticateUser(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockIAuthUsecase)(nil).AuthenticateUser), ctx, code)
}

// GetDiscordAuthURL mocks base method.
func (m *MockIAuthUsecase) GetDiscordAuthURL(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordAuthURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordAuthURL indicates an expected call of GetDiscordAuthURL.
func (mr *MockIAuthUsecaseMockRecorder) GetDiscordAuthURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordAuthURL", reflect.TypeOf((*MockIAuthUsecase)(nil).GetDiscordAuthURL), ctx)
}

// RegenerateToken mocks base method.
func (m *MockIAuthUsecase) RegenerateToken(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateToken", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegenerateToken indicates an expected call of RegenerateToken.
func (mr *MockIAuthUsecaseMockRecorder) RegenerateToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateToken", reflect.TypeOf((*MockIAuthUsecase)(nil).RegenerateToken), ctx, refreshToken)
}
