// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/tag.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/tag.go -destination=internal/interface/controller/mock/mock_tag_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockITagUseCase is a mock of ITagUseCase interface.
type MockITagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockITagUseCaseMockRecorder
	isgomock struct{}
}

// MockITagUseCaseMockRecorder is the mock recorder for MockITagUseCase.
type MockITagUseCaseMockRecorder struct {
	mock *MockITagUseCase
}

// NewMockITagUseCase creates a new mock instance.
func NewMockITagUseCase(ctrl *gomock.Controller) *MockITagUseCase {
	mock := &MockITagUseCase{ctrl: ctrl}
	mock.recorder = &MockITagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITagUseCase) EXPECT() *MockITagUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITagUseCase) Create(ctx context.Context, name string) (*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITagUseCaseMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITagUseCase)(nil).Create), ctx, name)
}

// GetAll mocks base method.
func (m *MockITagUseCase) GetAll(ctx context.Context) ([]*entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockITagUseCaseMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockITagUseCase)(nil).GetAll), ctx)
}
