// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"time"

	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"github.com/simesaba80/toybox-back/internal/domain/repository"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/comment"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/token"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/user"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/work"
	customejwt "github.com/simesaba80/toybox-back/internal/infrastructure/external/custome-jwt"
	"github.com/simesaba80/toybox-back/internal/infrastructure/external/oauth"
	"github.com/simesaba80/toybox-back/internal/infrastructure/router"
	"github.com/simesaba80/toybox-back/internal/interface/controller"
	"github.com/simesaba80/toybox-back/internal/usecase"
	"github.com/simesaba80/toybox-back/pkg/db"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

// InitializeApp はアプリケーションを初期化します
func InitializeApp() (*App, func(), error) {
	echo := ProvideEcho()
	db := ProvideDatabase()
	userRepository := user.NewUserRepository(db)
	iUserUseCase := ProvideUserUseCase(userRepository)
	userController := controller.NewUserController(iUserUseCase)
	workRepository := work.NewWorkRepository(db)
	iWorkUseCase := ProvideWorkUseCase(workRepository)
	workController := controller.NewWorkController(iWorkUseCase)
	commentRepository := comment.NewCommentRepository(db)
	commentUsecase := ProvideCommentUseCase(commentRepository, workRepository)
	commentController := controller.NewCommentController(commentUsecase)
	discordRepository := oauth.NewDiscordRepository()
	tokenProvider := ProvideTokenProvider()
	tokenRepository := token.NewTokenRepository(db)
	authUsecase := ProvideAuthUseCase(discordRepository, userRepository, tokenProvider, tokenRepository)
	authController := controller.NewAuthController(authUsecase)
	routerRouter := router.NewRouter(echo, userController, workController, commentController, authController)
	app := NewApp(routerRouter, db)
	return app, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(user.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*user.UserRepository)), work.NewWorkRepository, wire.Bind(new(repository.WorkRepository), new(*work.WorkRepository)), comment.NewCommentRepository, wire.Bind(new(repository.CommentRepository), new(*comment.CommentRepository)), oauth.NewDiscordRepository, wire.Bind(new(repository.DiscordRepository), new(*oauth.DiscordRepository)), token.NewTokenRepository, wire.Bind(new(repository.TokenRepository), new(*token.TokenRepository)))

var UseCaseSet = wire.NewSet(
	ProvideUserUseCase,
	ProvideWorkUseCase,
	ProvideCommentUseCase,
	ProvideAuthUseCase,
	ProvideTokenProvider,
)

var ControllerSet = wire.NewSet(controller.NewUserController, controller.NewWorkController, controller.NewCommentController, controller.NewAuthController)

var InfrastructureSet = wire.NewSet(
	ProvideDatabase, router.NewRouter, ProvideEcho,
)

// ProviderSet は依存関係を定義します
var ProviderSet = wire.NewSet(
	RepositorySet,
	UseCaseSet,
	ControllerSet,
	InfrastructureSet,
	NewApp,
)

// ProvideDatabase はデータベース接続を提供します
func ProvideDatabase() *bun.DB {
	db.Init()
	return db.DB
}

// ProvideUserUseCase はUserUseCaseを提供します
func ProvideUserUseCase(repo repository.UserRepository) usecase.IUserUseCase {
	return usecase.NewUserUseCase(repo, 30*time.Second)
}

// ProvideWorkUseCase はWorkUseCaseを提供します
func ProvideWorkUseCase(repo repository.WorkRepository) usecase.IWorkUseCase {
	return usecase.NewWorkUseCase(repo, 30*time.Second)
}

// ProvideCommentUseCase はCommentUseCaseを提供します
func ProvideCommentUseCase(commentRepo repository.CommentRepository, workRepo repository.WorkRepository) *usecase.CommentUsecase {
	return usecase.NewCommentUsecase(commentRepo, workRepo, 30*time.Second)
}

// ProvideDiscordUseCase はDiscordUseCaseを提供します
func ProvideAuthUseCase(authRepo repository.DiscordRepository, userRepo repository.UserRepository, tokenProvider usecase.TokenProvider, tokenRepo repository.TokenRepository) *usecase.AuthUsecase {
	return usecase.NewAuthUsecase(authRepo, userRepo, tokenProvider, tokenRepo)
}

// ProvideTokenProvider はTokenProviderを提供します
func ProvideTokenProvider() usecase.TokenProvider {
	return tokenProviderFunc(customejwt.GenerateToken)
}

type tokenProviderFunc func(userID string) (string, error)

func (f tokenProviderFunc) GenerateToken(userID string) (string, error) {
	return f(userID)
}

// ProvideEcho はEchoインスタンスを提供します
func ProvideEcho() *echo.Echo {
	return echo.New()
}

// NewApp はAppインスタンスを作成します
func NewApp(router2 *router.Router, database *bun.DB) *App {
	return &App{
		Router:   router2,
		Database: database,
	}
}

type App struct {
	Router   *router.Router
	Database *bun.DB
}

// Start アプリケーションの開始
func (app *App) Start() *echo.Echo {
	return app.Router.Setup()
}

// Cleanup アプリケーションのクリーンアップ
func (app *App) Cleanup() {
	if app.Database != nil {
		app.Database.Close()
	}
}
