// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/google/uuid"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"github.com/simesaba80/toybox-back/internal/domain/repository"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/asset"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/comment"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/favorite"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/tag"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/token"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/user"
	"github.com/simesaba80/toybox-back/internal/infrastructure/database/work"
	"github.com/simesaba80/toybox-back/internal/infrastructure/external/custome-jwt"
	"github.com/simesaba80/toybox-back/internal/infrastructure/external/oauth"
	"github.com/simesaba80/toybox-back/internal/infrastructure/router"
	"github.com/simesaba80/toybox-back/internal/interface/controller"
	"github.com/simesaba80/toybox-back/internal/usecase"
	"github.com/simesaba80/toybox-back/pkg/db"
	"github.com/simesaba80/toybox-back/pkg/s3_client"
	"github.com/uptrace/bun"
	"time"
)

// Injectors from wire.go:

// InitializeApp はアプリケーションを初期化します
func InitializeApp() (*App, func(), error) {
	echo := ProvideEcho()
	db := ProvideDatabase()
	userRepository := user.NewUserRepository(db)
	iUserUseCase := ProvideUserUseCase(userRepository)
	userController := controller.NewUserController(iUserUseCase)
	workRepository := work.NewWorkRepository(db)
	tagRepository := tag.NewTagRepository(db)
	iWorkUseCase := ProvideWorkUseCase(workRepository, tagRepository)
	workController := controller.NewWorkController(iWorkUseCase)
	commentRepository := comment.NewCommentRepository(db)
	iCommentUsecase := ProvideCommentUseCase(commentRepository, workRepository)
	commentController := controller.NewCommentController(iCommentUsecase)
	discordRepository := oauth.NewDiscordRepository()
	tokenProvider := ProvideTokenProvider()
	tokenRepository := token.NewTokenRepository(db)
	client := ProvideS3Client()
	assetRepository := asset.NewAssetRepository(db, client)
	iAuthUsecase := ProvideAuthUseCase(discordRepository, userRepository, tokenProvider, tokenRepository, assetRepository)
	authController := controller.NewAuthController(iAuthUsecase)
	iAssetUseCase := ProvideAssetUseCase(assetRepository)
	assetController := controller.NewAssetController(iAssetUseCase)
	favoriteRepository := favorite.NewFavoriteRepository(db)
	iFavoriteUsecase := ProvideFavoriteUseCase(favoriteRepository)
	favoriteController := controller.NewFavoriteController(iFavoriteUsecase)
	iTagUseCase := ProvideTagUseCase(tagRepository)
	tagController := controller.NewTagController(iTagUseCase)
	routerRouter := router.NewRouter(echo, userController, workController, commentController, authController, assetController, favoriteController, tagController)
	app := NewApp(routerRouter, db, client)
	return app, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(user.NewUserRepository, wire.Bind(new(repository.UserRepository), new(*user.UserRepository)), work.NewWorkRepository, wire.Bind(new(repository.WorkRepository), new(*work.WorkRepository)), comment.NewCommentRepository, wire.Bind(new(repository.CommentRepository), new(*comment.CommentRepository)), oauth.NewDiscordRepository, wire.Bind(new(repository.DiscordRepository), new(*oauth.DiscordRepository)), token.NewTokenRepository, wire.Bind(new(repository.TokenRepository), new(*token.TokenRepository)), asset.NewAssetRepository, wire.Bind(new(repository.AssetRepository), new(*asset.AssetRepository)), favorite.NewFavoriteRepository, wire.Bind(new(repository.FavoriteRepository), new(*favorite.FavoriteRepository)), tag.NewTagRepository, wire.Bind(new(repository.TagRepository), new(*tag.TagRepository)))

var UseCaseSet = wire.NewSet(
	ProvideUserUseCase,
	ProvideWorkUseCase,
	ProvideCommentUseCase,
	ProvideAuthUseCase,
	ProvideTokenProvider,
	ProvideAssetUseCase,
	ProvideFavoriteUseCase,
	ProvideTagUseCase,
)

var ControllerSet = wire.NewSet(controller.NewUserController, controller.NewWorkController, controller.NewCommentController, controller.NewAuthController, controller.NewAssetController, controller.NewFavoriteController, controller.NewTagController)

var InfrastructureSet = wire.NewSet(
	ProvideDatabase,
	ProvideS3Client, router.NewRouter, ProvideEcho,
)

// ProviderSet は依存関係を定義します
var ProviderSet = wire.NewSet(
	RepositorySet,
	UseCaseSet,
	ControllerSet,
	InfrastructureSet,
	NewApp,
)

// ProvideDatabase はデータベース接続を提供します
func ProvideDatabase() *bun.DB {
	db.Init()
	return db.DB
}

func ProvideS3Client() *s3.Client {
	s3_client.Init()
	return s3_client.Client
}

// ProvideUserUseCase はUserUseCaseを提供します
func ProvideUserUseCase(repo repository.UserRepository) usecase.IUserUseCase {
	return usecase.NewUserUseCase(repo)
}

// ProvideWorkUseCase はWorkUseCaseを提供します
func ProvideWorkUseCase(workRepo repository.WorkRepository, tagRepo repository.TagRepository) usecase.IWorkUseCase {
	return usecase.NewWorkUseCase(workRepo, tagRepo)
}

// ProvideCommentUseCase はCommentUseCaseを提供します
func ProvideCommentUseCase(commentRepo repository.CommentRepository, workRepo repository.WorkRepository) usecase.ICommentUsecase {
	return usecase.NewCommentUsecase(commentRepo, workRepo, 30*time.Second)
}

// ProvideDiscordUseCase はDiscordUseCaseを提供します
func ProvideAuthUseCase(authRepo repository.DiscordRepository, userRepo repository.UserRepository, tokenProvider usecase.TokenProvider, tokenRepo repository.TokenRepository, assetRepo repository.AssetRepository) usecase.IAuthUsecase {
	return usecase.NewAuthUsecase(authRepo, userRepo, tokenProvider, tokenRepo, assetRepo)
}

// ProvideTokenProvider はTokenProviderを提供します
func ProvideTokenProvider() usecase.TokenProvider {
	return tokenProviderFunc(customejwt.GenerateToken)
}

type tokenProviderFunc func(userID uuid.UUID) (string, error)

func (f tokenProviderFunc) GenerateToken(userID uuid.UUID) (string, error) {
	return f(userID)
}

// ProvideAssetUseCase はAssetUseCaseを提供します
func ProvideAssetUseCase(assetRepo repository.AssetRepository) usecase.IAssetUseCase {
	return usecase.NewAssetUseCase(assetRepo)
}

// ProvideFavoriteUseCase はFavoriteUseCaseを提供します
func ProvideFavoriteUseCase(favoriteRepo repository.FavoriteRepository) usecase.IFavoriteUsecase {
	return usecase.NewFavoriteUsecase(favoriteRepo)
}

// ProvideTagUseCase はTagUseCaseを提供します
func ProvideTagUseCase(tagRepo repository.TagRepository) usecase.ITagUseCase {
	return usecase.NewTagUseCase(tagRepo)
}

// ProvideEcho はEchoインスタンスを提供します
func ProvideEcho() *echo.Echo {
	return echo.New()
}

// NewApp はAppインスタンスを作成します
func NewApp(router2 *router.Router, database *bun.DB, s3Client *s3.Client) *App {
	return &App{
		Router:   router2,
		Database: database,
		S3Client: s3Client,
	}
}

type App struct {
	Router   *router.Router
	Database *bun.DB
	S3Client *s3.Client
}

// Start アプリケーションの開始
func (app *App) Start() *echo.Echo {
	return app.Router.Setup()
}

// Cleanup アプリケーションのクリーンアップ
func (app *App) Cleanup() {
	if app.Database != nil {
		app.Database.Close()
	}
}
