// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/work.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/work.go -destination=internal/interface/controller/mock_work_usecase.go -package=controller
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/simesaba80/toybox-back/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkUseCase is a mock of WorkUseCase interface.
type MockWorkUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWorkUseCaseMockRecorder
	isgomock struct{}
}

// MockWorkUseCaseMockRecorder is the mock recorder for MockWorkUseCase.
type MockWorkUseCaseMockRecorder struct {
	mock *MockWorkUseCase
}

// NewMockWorkUseCase creates a new mock instance.
func NewMockWorkUseCase(ctrl *gomock.Controller) *MockWorkUseCase {
	mock := &MockWorkUseCase{ctrl: ctrl}
	mock.recorder = &MockWorkUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkUseCase) EXPECT() *MockWorkUseCaseMockRecorder {
	return m.recorder
}

// CreateWork mocks base method.
func (m *MockWorkUseCase) CreateWork(ctx context.Context, title, description, visibility string, userID uuid.UUID) (*entity.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWork", ctx, title, description, visibility, userID)
	ret0, _ := ret[0].(*entity.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWork indicates an expected call of CreateWork.
func (mr *MockWorkUseCaseMockRecorder) CreateWork(ctx, title, description, visibility, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWork", reflect.TypeOf((*MockWorkUseCase)(nil).CreateWork), ctx, title, description, visibility, userID)
}

// GetAll mocks base method.
func (m *MockWorkUseCase) GetAll(ctx context.Context, limit, page *int) ([]*entity.Work, int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, page)
	ret0, _ := ret[0].([]*entity.Work)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWorkUseCaseMockRecorder) GetAll(ctx, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWorkUseCase)(nil).GetAll), ctx, limit, page)
}

// GetByID mocks base method.
func (m *MockWorkUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkUseCase)(nil).GetByID), ctx, id)
}
